<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TomorowMind.Genesis.Application\TomorowMind.Genesis.Application.csproj" />
    <ProjectReference Include="..\TomorowMind.Genesis.Domain\TomorowMind.Genesis.Domain.csproj" />
    <ProjectReference Include="..\TomorowMind.Genesis.Infrastructure\TomorowMind.Genesis.Infrastructure.csproj" />
  </ItemGroup>

</Project>
